# Generated by Django 5.2.7 on 2025-11-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="img", upload_to=""),
            preserve_default=False,
        ),
    ]
