# Generated by Django 5.2.7 on 2025-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
