# Generated by Django 5.2.7 on 2025-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Card'), (2, 'Transfer'), (3, 'Cash')], default=3),
        ),
    ]
