# Generated by Django 5.2.7 on 2026-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Standard shipping'), (2, 'Express shipping'), (3, 'Overnight shipping')], default=1),
            preserve_default=False,
        ),
    ]
