# Generated by Django 5.2.7 on 2026-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(1, 'Standard shipping'), (2, 'Express shipping'), (3, 'Overnight shipping')], unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping option',
                'verbose_name_plural': 'Shipping options',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
    ]
