# Generated by Django 5.2.7 on 2026-02-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_product_image_product_brand_specification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
