# Generated by Django 5.2.7 on 2026-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_order_address_order_city_order_save_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
