# Generated by Django 5.2.7 on 2026-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingoption',
            name='delivery_time',
            field=models.CharField(default='same day', help_text="e.g. '1–2 business days', '3–5 days', 'Same day'", max_length=50),
            preserve_default=False,
        ),
    ]
