# Generated by Django 5.2.7 on 2026-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shippingoption_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
